### ISSUE TITLE
Running as root?

### ISSUE THREAD

**Issue by jensenbox** [nickjj/docker-django-example#3]
Is there any concern that the primary container is running as root? I know it is a container but I have heard that it is good practice to run as a non-root user.

**Comment by nickjj** [comment]
Hi, it's not running as the root user. It gets switched to the `python` user.

**Comment by jensenbox** [comment]
Yeah I finally saw that. Running as the Python user made my eyes glance
over it and not see it..

Total nitpick but perhaps change the user to something like application
instead of Python or something else that would stand out a little bit more.
Not a big deal though.

**Comment by nickjj** [comment]
Thanks, I went with `python` because it's something most official Docker images use as a naming convention. When they include a user created in the image, it's with the name of the image itself.

If you head to https://nickjanetakis.com/blog/best-practices-around-production-ready-web-apps-with-docker-compose and search for "I chose python" you'll find a paragraph of text going into detail about this.
