### ISSUE TITLE
No module named 'distutils'

### ISSUE THREAD

**Issue by kennyhei** [nickjj/docker-django-example#53]
Got this error on macOS when I was trying to setup my project. My python version was 3.12.5. Apparently distutils has been removed in python 3.12.

Managed to fix it by adding `setuptools==74.1.2` in `requirements.txt` and ran `docker compose up --build` again.

**Comment by nickjj** [comment]
Hi,

Thanks. It looks like a week ago https://github.com/docker-library/python/pull/954 the official Python 3.12.5 image was changed to remove this. Prior to that it was installing that package. This project wasn't built in CI within a week.

When I build the image locally with `docker compose build --no-cache` I am able to reproduce the problem.

I just pushed https://github.com/nickjj/docker-django-example/commit/ea3ce5c451df49eff67ad3603a4315e1e785cb8e to fix it.

**Comment by kennyhei** [comment]
Wow, that was fast! Thanks 🚀

**Comment by nickjj** [comment]
No problem, thanks to this issue I'm going to look into using GitHub Action's `schedule` feature to run CI every day so things like this get caught in an automated way since I'd get emailed if a build fails.

**Comment by edmorley** [comment]
I was curious whether it was a broken dependency of this project that was missing the setuptools dependency (and if so, was going to report that upstream), however, trying out a build locally I see the issue was from a first-party usage of `distutils`'s `strtobool`:

```
worker-1    |   File "/app/src/config/settings.py", line 16, in <module>
worker-1    |     from distutils.util import strtobool
worker-1    | ModuleNotFoundError: No module named 'distutils'
```

Checking https://peps.python.org/pep-0632/#migration-advice it seems there isn't an official replacement for `strtobool` - but if you wanted to avoid having to have the entirety of setuptools as a dependency you could either:
1. Switch to the third-party `str2bool` package: https://github.com/symonsoft/str2bool
2. Vendor the `strtobool` function from distutils directly (since it's <10 lines): https://github.com/pypa/distutils/blob/bddd2591d35cf59b2a0d54156b195c334ab7dc8a/distutils/util.py#L329-L342

**Comment by nickjj** [comment]
Thanks, I remember thinking about this back when 3.12 dropped and I was undecided.

That `str2bool` package isn't backwards compatible with the one that's in distutils because it doesn't include `on` and `off` and uses a different function name. I also wasn't crazy about introducing a `lib/` directory to drop in nothing more than a `strtobool` function so I left it be for now.

But maybe the `lib/` directory idea isn't bad because it does provide an opinion on where to keep general non-project specific code that's not pulled in from a third party dependency.
