### ISSUE TITLE
Getting Server Error (500) on debug=false on env file

### ISSUE THREAD

**Issue by pramishp** [nickjj/docker-django-example#6]
thank you for this excellent docker django example. I am getting 500 on setting debug=false in env file

![image](https://user-images.githubusercontent.com/15194546/132087640-6cf8a302-b8bc-4ea6-ba75-13b7e3eba279.png)

**Comment by nickjj** [comment]
Hi,

After setting that value did you run a `docker-compose build` before upping it?

**Comment by nickjj** [comment]
Ah I know what happened.

If you're going to set `DEBUG=false` you also need to set `NODE_ENV=production`. If you don't set node to production then Django's collectstatic won't find any assets and when you visit the home page you'll get a 500 which throws `ValueError: Missing staticfiles manifest entry for 'css/app.css'`.

You can find the real cause of the 500 with `DEBUG=false` if you goto the settings and put `DEBUG_PROPAGATE_EXCEPTIONS = True`.

To properly emulate production on a real server you'll want to run:

- `./run clean`
- In the `.env` file comment out `export DOCKER_WEB_VOLUME=.:/app`
- `docker-compose down -v --remove-orphans`
- `docker-compose build`
- `docker-compose up`

Now it should work.

It's really important to run the build command because that's going to ensure collectstatic gets run.

**Comment by nickjj** [comment]
I'm going to close this one since the above is very likely the case. Feel free to re-open it if it's not.
